### ISSUE TITLE
Desktop Wireframes

### ISSUE THREAD

**Issue by code-warrior** [the-modular-grid/the-modular-grid.github.io#4]
Let’s loop back on this by 15 July.

**Comment by betron** [comment]
This is the first draft of a pen and paper wireframe for the desktop layout. 

![wireframedesktop](https://user-images.githubusercontent.com/2722221/28080110-bf09b0fe-6638-11e7-843e-f9289f980247.jpg)

**Comment by code-warrior** [comment]
The content in issue #2 has been updated, @betron. It should now be easier to re-arrange the content in sections `#1` and `#9` in your diagram.

**Comment by betron** [comment]
Second Draft of the Wireframe for the Desktop layout. 
![wireframev2](https://user-images.githubusercontent.com/2722221/28286230-7ab45356-6b05-11e7-9d9e-9b7b455c0b98.jpg)

**Comment by code-warrior** [comment]
Nicely done. I think we can now move on to phase 2.

**Comment by code-warrior** [comment]
Implemented in the `https://github.com/the-modular-grid/wireframes` repo.
